version: "1"
rules:
  - base: main
    upstream: swiftlang:main
    mergeMethod: hardreset
    assignees:
      - kkebo
    reviewers:
      - kkebo
  - base: wasm32-wasi-test
    upstream: main
    mergeMethod: merge
    assignees:
      - kkebo
    reviewers:
      - kkebo
