name: Pull request

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  tests:
    name: Test
    uses: swiftlang/github-workflows/.github/workflows/swift_package_test.yml@main
  soundness:
    name: Soundness
    uses: swiftlang/github-workflows/.github/workflows/soundness.yml@main
    with:
      api_breakage_check_allowlist_path: "Release Notes/api-breakages.txt"
      # https://github.com/swiftlang/swift-syntax/issues/2987
      docs_check_enabled: false
      # https://github.com/swiftlang/swift-syntax/issues/2988
      format_check_enabled: false
