# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: test

on:
  push:
    branches: [ "wasm32-wasi-test" ]
  pull_request:
    branches: [ "wasm32-wasi-test" ]

jobs:
  build:

    runs-on: macos-12

    steps:
    - uses: actions/checkout@v3
    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode_14.1.app
    - name: Install Wasmer
      run: brew install wasmer
    - name: Install Wasm Toolchain
      run: |
        VERSION=swift-wasm-DEVELOPMENT-SNAPSHOT-2022-10-04-a
        TOOLCHAIN_URL="https://github.com/swiftwasm/swift/releases/download/$VERSION/$VERSION-macos_x86_64.pkg"
        curl -LO $TOOLCHAIN_URL
        installer -target CurrentUserHomeDirectory -pkg $VERSION-macos_x86_64.pkg
        echo "PATH=$HOME/Library/Developer/Toolchains/$VERSION.xctoolchain/usr/bin:${PATH}" >> $GITHUB_ENV
    - name: Build
      run: swift build -c release --build-tests --triple wasm32-unknown-wasi -Xlinker -z -Xlinker stack-size=262144
    - name: Run tests
      run: wasmer --dir / .build/release/SwiftSyntaxPackageTests.wasm
