name: test
on:
  push:
    branches: ["wasm32-wasi-test"]
  pull_request:
    branches: ["wasm32-wasi-test"]
jobs:
  test:
    runs-on: ubuntu-latest
    container: swiftlang/swift:nightly-main-jammy@sha256:1b268c87e283f79f3989fe1d96009d910dd8990a07ed2dae7a8e445a01cda9f2
    env:
      STACK_SIZE: 16777216
    steps:
      - uses: actions/checkout@v4
      - uses: bytecodealliance/actions/wasmtime/setup@v1
      - run: swift --version
      - run: wasmtime -V
      - run: swift sdk install https://github.com/swiftwasm/swift/releases/download/swift-wasm-DEVELOPMENT-SNAPSHOT-2024-05-01-a/swift-wasm-DEVELOPMENT-SNAPSHOT-2024-05-01-a-wasm32-unknown-wasi.artifactbundle.zip
      - run: swift build -c release --build-tests --swift-sdk wasm32-unknown-wasi -Xlinker -z -Xlinker stack-size=$STACK_SIZE
      - run: wasmtime --dir / --wasm max-wasm-stack=$STACK_SIZE .build/release/swift-syntaxPackageTests.wasm
